CREATE DATABASE InventoryAPI

CREATE TABLE Product (
	ID INT IDENTITY PRIMARY KEY,
	Name NVARCHAR(50),
	Description NVARCHAR(100),
	SKU NVARCHAR(100),
	Price DECIMAL(18,2),
	CreatedAt DATETIME,
	CreatedBy NVARCHAR(50),
	LastUpdatedAt DATETIME,
	LastUpdatedBy NVARCHAR(50)
)

CREATE TABLE Stock (
	ID INT IDENTITY PRIMARY KEY,
	Product_Id INT FOREIGN KEY REFERENCES PRODUCT(ID),
	Quantity INT,
	CreatedAt DATETIME,
	CreatedBy NVARCHAR(50),
	LastUpdatedAt DATETIME,
	LastUpdatedBy NVARCHAR(50)
)
