CREATE DATABASE InventoryAPI

CREATE TABLE Product (
	ID INT IDENTITY PRIMARY KEY,
	Name NVARCHAR,
	Description NVARCHAR,
	SKU NVARCHAR,
	Price DECIMAL(18,2),
	CreatedAt DATETIME,
	CreatedBy NVARCHAR,
	LastUpdatedAt DATETIME,
	LastUpdatedBy NVARCHAR
)

CREATE TABLE Stock (
	ID INT IDENTITY PRIMARY KEY,
	Product_Id INT FOREIGN KEY REFERENCES PRODUCT(ID),
	Quantity INT,
	CreatedAt DATETIME,
	CreatedBy NVARCHAR,
	LastUpdatedAt DATETIME,
	LastUpdatedBy NVARCHAR
)